name: .Net Build Arcade Client

on:
  push:
    branches: master
      
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: .NET 5 Application
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x            
    - name: Build with dotnet
      run: dotnet build -c Release -o ./build ./src/tomi.arcade.client/tomi.arcade.client.csproj
